### ISSUE TITLE
Support for song play history

### ISSUE THREAD

**Issue by surrealroad** [Mystogan98/BeatSaviorData#11]
The author of the songplayhistory mod has discontinued that plugin and suggested to request it being incorporated into this one (https://github.com/swift-kim/SongPlayHistory/releases/tag/1.5.3). So I'm making that request 😄

**Comment by Mystogan98** [comment]
Hello,

Sadly BSD only tracks the last ~month of play (because BSD trackers are huge), so I won't be able to show the full history. I also already take about forever to implement the functionality I've already promised, so I'll have to refuse the request, sorry.

(On a side note, I plan to add a history to BSD allowing you to see your last ~month of stats. It will be able to display the full info panel for every song, but it won't be as easily accessible as SongPlayHistory was.)
